### ISSUE TITLE
Kinesis stream - not in GZIP format

### ISSUE THREAD

**Issue by epierce78** [Graylog2/graylog-plugin-aws#86] opened 2018-09-25 13:04 UTC
I've got a fresh install of Graylog 2.4.6 on Ubuntu 18.04.  I've set up a Kinesis stream to receive Cloudwatch Log events and process them into Graylog.  (I think we'll do filtering in Graylog, if we can, rather than on the AWS side, as there may be new log streams we want to ingest freqently).

Anyway, once configured, I receive the following exception from the plugin:

`java.util.zip.ZipException: Not in GZIP format
	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:165) ~[?:1.8.0_181]
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79) ~[?:1.8.0_181]
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91) ~[?:1.8.0_181]
	at org.graylog2.plugin.Tools.decompressGzip(Tools.java:235) ~[graylog.jar:?]
	at org.graylog2.plugin.Tools.decompressGzip(Tools.java:223) ~[graylog.jar:?]
	at org.graylog.aws.kinesis.KinesisConsumer$1.processRecords(KinesisConsumer.java:108) [graylog-plugin-aws-2.4.6.jar:?]
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ProcessTask.callProcessRecords(ProcessTask.java:221) [graylog-plugin-aws-2.4.6.jar:?]
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ProcessTask.call(ProcessTask.java:176) [graylog-plugin-aws-2.4.6.jar:?]
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:49) [graylog-plugin-aws-2.4.6.jar:?]
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:24) [graylog-plugin-aws-2.4.6.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]`

I looked into this a bit, and ran some AWS CLI commands to debug:
`aws kinesis get-shard-iterator --stream-name cloudwatch_logs --shard-id shardId ...`
`aws kinesis get-records --shard-iterator ...`

When grabbing the logs this way, it appears the data section is base64 encoded and not gzipped.  I don't know if that's a recent API change; the AWS documentation appears to also be incorrect in this matter as they suggest it is gzipped as well.

This link (https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/RelayEventsKinesisStream.html) does not suggest they are gzipped however.

Any insight on this would be appreciated.

**Comment by agtcovert** [comment] 2018-09-26 21:52
To provide some additional information, the data on the Kinesis stream looks like this:
`        {
            "SequenceNumber": "49588570039560669873433680102537011752139567696304930818",
            "ApproximateArrivalTimestamp": 1537919012.95,
            "Data": "eyJ2ZXJzaW9uIjoiMCIsImlkIjoiMjJlOTAxZmEtOTk0ZS1mZjdhLWU4NTMtOTgzNmVkYWI1OWFhIiwiZGV0YWlsLXR5cGUiOiJBV1MgQVBJIENhbGwgdmlhIENsb3VkVHJhaWwiLCJzb3VyY2UiOiJhd3MubG9ncyIsImFjY291bnQiOiI2OTcxODcwMjY2ODUiLCJ0aW1lIjoiMjAxOC0wOS0yNVQyMzo0MzowOFoiLCJyZWdpb24iOiJldS13ZXN0LTEiLCJyZXNvdXJjZXMiOltdLCJkZXRhaWwiOnsiZXZlbnRWZXJzaW9uIjoiMS4wNCIsInVzZXJJZGVudGl0eSI6eyJ0eXBlIjoiQXNzdW1lZFJvbGUiLCJwcmluY2lwYWxJZCI6IkFST0FKN1RUQ1EzNlNaU1JFMlNJVzphZGVzYXdvcmxkX2F1Y3Rpb250eXBlc19nZXQiLCJhcm4iOiJhcm46YXdzOnN0czo6Njk3MTg3MDI2Njg1OmFzc3VtZWQtcm9sZS9BZGVzYVdvcmxkU2VhcmNoTGFtYmRhL2FkZXNhd29ybGRfYXVjdGlvbnR5cGVzX2dldCIsImFjY291bnRJZCI6IjY5NzE4NzAyNjY4NSIsImFjY2Vzc0tleUlkIjoiQVNJQTJFVTRWWTM2NUZFTFpaRloiLCJzZXNzaW9uQ29udGV4dCI6eyJhdHRyaWJ1dGVzIjp7Im1mYUF1dGhlbnRpY2F0ZWQiOiJmYWxzZSIsImNyZWF0aW9uRGF0ZSI6IjIwMTgtMDktMjVUMjI6MjA6NTlaIn0sInNlc3Npb25Jc3N1ZXIiOnsidHlwZSI6IlJvbGUiLCJwcmluY2lwYWxJZCI6IkFST0FKN1RUQ1EzNlNaU1JFMlNJVyIsImFybiI6ImFybjphd3M6aWFtOjo2OTcxODcwMjY2ODU6cm9sZS9BZGVzYVdvcmxkU2VhcmNoTGFtYmRhIiwiYWNjb3VudElkIjoiNjk3MTg3MDI2Njg1IiwidXNlck5hbWUiOiJBZGVzYVdvcmxkU2VhcmNoTGFtYmRhIn19fSwiZXZlbnRUaW1lIjoiMjAxOC0wOS0yNVQyMzo0MzowOFoiLCJldmVudFNvdXJjZSI6ImxvZ3MuYW1hem9uYXdzLmNvbSIsImV2ZW50TmFtZSI6IkNyZWF0ZUxvZ1N0cmVhbSIsImF3c1JlZ2lvbiI6ImV1LXdlc3QtMSIsInNvdXJjZUlQQWRkcmVzcyI6IjE4LjIwMi41Ni4yMzciLCJ1c2VyQWdlbnQiOiJhd3NsYW1iZGEtd29ya2VyIiwicmVxdWVzdFBhcmFtZXRlcnMiOnsibG9nR3JvdXBOYW1lIjoiL2F3cy9sYW1iZGEvYWRlc2F3b3JsZF9hdWN0aW9udHlwZXNfZ2V0IiwibG9nU3RyZWFtTmFtZSI6IjIwMTgvMDkvMjUvWyRMQVRFU1RdNjNlODcyOTZlMmFjNDE5NTk2NmVjNDU5YjFjMzRjYTYifSwicmVzcG9uc2VFbGVtZW50cyI6bnVsbCwicmVxdWVzdElEIjoiYzEzOWRkMjAtYzExYy0xMWU4LWI0YTktMmIyYTlkMGQ2MGRlIiwiZXZlbnRJRCI6IjQyNDM5YzNiLTgyMjgtNGQ4ZC1hMTMzLTg4ZGQwZTlmYmRjZSIsImV2ZW50VHlwZSI6IkF3c0FwaUNhbGwiLCJhcGlWZXJzaW9uIjoiMjAxNDAzMjgifX0=",
            "PartitionKey": "22e901fa-994e-ff7a-e853-9836edab59aa_55d3dca1-baca-6814-0dfc-c3b9eefa056c"
        },
        {
            "SequenceNumber": "49588570039560669873433680102538220677959182875235450882",
            "ApproximateArrivalTimestamp": 1537919021.181,
            "Data": "eyJ2ZXJzaW9uIjoiMCIsImlkIjoiYmQwNjFiMTAtM2Y5My03N2NkLWNlZTgtYTg5NDViNjMyZGI3IiwiZGV0YWlsLXR5cGUiOiJBV1MgQVBJIENhbGwgdmlhIENsb3VkVHJhaWwiLCJzb3VyY2UiOiJhd3MubG9ncyIsImFjY291bnQiOiI2OTcxODcwMjY2ODUiLCJ0aW1lIjoiMjAxOC0wOS0yNVQyMzo0MzoxNFoiLCJyZWdpb24iOiJldS13ZXN0LTEiLCJyZXNvdXJjZXMiOltdLCJkZXRhaWwiOnsiZXZlbnRWZXJzaW9uIjoiMS4wNCIsInVzZXJJZGVudGl0eSI6eyJ0eXBlIjoiQXNzdW1lZFJvbGUiLCJwcmluY2lwYWxJZCI6IkFST0FKN1RUQ1EzNlNaU1JFMlNJVzphZGVzYXdvcmxkX3RheHR5cGVzX2dldCIsImFybiI6ImFybjphd3M6c3RzOjo2OTcxODcwMjY2ODU6YXNzdW1lZC1yb2xlL0FkZXNhV29ybGRTZWFyY2hMYW1iZGEvYWRlc2F3b3JsZF90YXh0eXBlc19nZXQiLCJhY2NvdW50SWQiOiI2OTcxODcwMjY2ODUiLCJhY2Nlc3NLZXlJZCI6IkFTSUEyRVU0VlkzNlhUVFNSR1VWIiwic2Vzc2lvbkNvbnRleHQiOnsiYXR0cmlidXRlcyI6eyJtZmFBdXRoZW50aWNhdGVkIjoiZmFsc2UiLCJjcmVhdGlvbkRhdGUiOiIyMDE4LTA5LTI1VDIyOjIxOjA4WiJ9LCJzZXNzaW9uSXNzdWVyIjp7InR5cGUiOiJSb2xlIiwicHJpbmNpcGFsSWQiOiJBUk9BSjdUVENRMzZTWlNSRTJTSVciLCJhcm4iOiJhcm46YXdzOmlhbTo6Njk3MTg3MDI2Njg1OnJvbGUvQWRlc2FXb3JsZFNlYXJjaExhbWJkYSIsImFjY291bnRJZCI6IjY5NzE4NzAyNjY4NSIsInVzZXJOYW1lIjoiQWRlc2FXb3JsZFNlYXJjaExhbWJkYSJ9fX0sImV2ZW50VGltZSI6IjIwMTgtMDktMjVUMjM6NDM6MTRaIiwiZXZlbnRTb3VyY2UiOiJsb2dzLmFtYXpvbmF3cy5jb20iLCJldmVudE5hbWUiOiJDcmVhdGVMb2dTdHJlYW0iLCJhd3NSZWdpb24iOiJldS13ZXN0LTEiLCJzb3VyY2VJUEFkZHJlc3MiOiIxOC4yMDIuNTYuMjM3IiwidXNlckFnZW50IjoiYXdzbGFtYmRhLXdvcmtlciIsInJlcXVlc3RQYXJhbWV0ZXJzIjp7ImxvZ1N0cmVhbU5hbWUiOiIyMDE4LzA5LzI1L1skTEFURVNUXWY2Zjk5MTY1NTczNjQ5MmY5MGZlNGIxN2JlYjdkOWNlIiwibG9nR3JvdXBOYW1lIjoiL2F3cy9sYW1iZGEvYWRlc2F3b3JsZF90YXh0eXBlc19nZXQifSwicmVzcG9uc2VFbGVtZW50cyI6bnVsbCwicmVxdWVzdElEIjoiYzUzOGQwYTgtYzExYy0xMWU4LTgzMWUtMzkyZjIxNmMyNTNkIiwiZXZlbnRJRCI6ImViNmYwNGNjLTU0YWUtNDZiOS1hNGRiLTk1ODU5NzM2M2RmMyIsImV2ZW50VHlwZSI6IkF3c0FwaUNhbGwiLCJhcGlWZXJzaW9uIjoiMjAxNDAzMjgifX0=",
            "PartitionKey": "bd061b10-3f93-77cd-cee8-a8945b632db7_89324c2e-2e7f-5128-4257-51a9be87447f"
        },
        {
            "SequenceNumber": "49588570039560669873433680102539429603778797848007540738",
            "ApproximateArrivalTimestamp": 1537919026.094,
            "Data": "eyJ2ZXJzaW9uIjoiMCIsImlkIjoiYTc5NGZkZjEtZjJmYy0wMzk0LWNjZDItZDY3ZWEwZmIzZWFiIiwiZGV0YWlsLXR5cGUiOiJBV1MgQVBJIENhbGwgdmlhIENsb3VkVHJhaWwiLCJzb3VyY2UiOiJhd3MubG9ncyIsImFjY291bnQiOiI2OTcxODcwMjY2ODUiLCJ0aW1lIjoiMjAxOC0wOS0yNVQyMzo0MzoxMFoiLCJyZWdpb24iOiJldS13ZXN0LTEiLCJyZXNvdXJjZXMiOltdLCJkZXRhaWwiOnsiZXZlbnRWZXJzaW9uIjoiMS4wNCIsInVzZXJJZGVudGl0eSI6eyJ0eXBlIjoiQXNzdW1lZFJvbGUiLCJwcmluY2lwYWxJZCI6IkFST0FKN1RUQ1EzNlNaU1JFMlNJVzphZGVzYXdvcmxkX2ludmVudG9yeXR5cGVzX2dldCIsImFybiI6ImFybjphd3M6c3RzOjo2OTcxODcwMjY2ODU6YXNzdW1lZC1yb2xlL0FkZXNhV29ybGRTZWFyY2hMYW1iZGEvYWRlc2F3b3JsZF9pbnZlbnRvcnl0eXBlc19nZXQiLCJhY2NvdW50SWQiOiI2OTcxODcwMjY2ODUiLCJhY2Nlc3NLZXlJZCI6IkFTSUEyRVU0VlkzNjRITDJITDdDIiwic2Vzc2lvbkNvbnRleHQiOnsiYXR0cmlidXRlcyI6eyJtZmFBdXRoZW50aWNhdGVkIjoiZmFsc2UiLCJjcmVhdGlvbkRhdGUiOiIyMDE4LTA5LTI1VDIyOjIxOjAxWiJ9LCJzZXNzaW9uSXNzdWVyIjp7InR5cGUiOiJSb2xlIiwicHJpbmNpcGFsSWQiOiJBUk9BSjdUVENRMzZTWlNSRTJTSVciLCJhcm4iOiJhcm46YXdzOmlhbTo6Njk3MTg3MDI2Njg1OnJvbGUvQWRlc2FXb3JsZFNlYXJjaExhbWJkYSIsImFjY291bnRJZCI6IjY5NzE4NzAyNjY4NSIsInVzZXJOYW1lIjoiQWRlc2FXb3JsZFNlYXJjaExhbWJkYSJ9fX0sImV2ZW50VGltZSI6IjIwMTgtMDktMjVUMjM6NDM6MTBaIiwiZXZlbnRTb3VyY2UiOiJsb2dzLmFtYXpvbmF3cy5jb20iLCJldmVudE5hbWUiOiJDcmVhdGVMb2dTdHJlYW0iLCJhd3NSZWdpb24iOiJldS13ZXN0LTEiLCJzb3VyY2VJUEFkZHJlc3MiOiIxOC4yMDIuNTYuMjM3IiwidXNlckFnZW50IjoiYXdzbGFtYmRhLXdvcmtlciIsInJlcXVlc3RQYXJhbWV0ZXJzIjp7ImxvZ0dyb3VwTmFtZSI6Ii9hd3MvbGFtYmRhL2FkZXNhd29ybGRfaW52ZW50b3J5dHlwZXNfZ2V0IiwibG9nU3RyZWFtTmFtZSI6IjIwMTgvMDkvMjUvWyRMQVRFU1RdZGY5OGNhODI0ZWM0NGZmMzhmZDI0MTRhZGQ4Y2Y4NGQifSwicmVzcG9uc2VFbGVtZW50cyI6bnVsbCwicmVxdWVzdElEIjoiYzI4ZWU2YjAtYzExYy0xMWU4LThiYTYtODdkNTZiMTBkMTBhIiwiZXZlbnRJRCI6IjYxNmI0MDQ3LTIzMDAtNGRhNS1iNDVkLTk2NDlhNWIwMThhYSIsImV2ZW50VHlwZSI6IkF3c0FwaUNhbGwiLCJhcGlWZXJzaW9uIjoiMjAxNDAzMjgifX0=",
            "PartitionKey": "a794fdf1-f2fc-0394-ccd2-d67ea0fb3eab_ca4ff563-763f-8f19-af71-3f5691618e38"
        },
`

The data element in each is base64 encoded only.  I forked the repo, and it's fairly trivial to put in a check to see if the stream is GZIPPed or not.  However, the underlying classes & codecs are not expecting this JSON payload from what I can tell.

I'm starting to suspect I'm using this in a different, unintended or unsupported way currently.

The CloudWatch -> Kinesis relationship is basically a catchall for anything coming in from CloudWatch.  We do a lot with Lambda functions, and I'd like to be able to index/search/etc. on what gets logged to CloudWatch.  In its native form (CloudWatch), is not terribly user-friendly, especially when there are over 300 lambdas deployed.

In looking at the code, I understand the KinsesisConsumer.java well enough, but I don't yet understand the underpinnings of how the plugin decides which codec and `org.graylog.aws.cloudwatch...` class to utilize for parsing out a message.  If I can get a better understanding of that, I might be able to provide a patch to support this use case.

Again, help/insight very appreciated.  Hopefully this sheds more light on what I'm doing.

**Comment by agtcovert** [comment] 2018-09-27 17:59
I've forked the repo and implemented support for this.  See here: [https://github.com/agtcovert/graylog-plugin-aws/commit/957aca38de32f60cf28f8415cfc5afc9c3d6b4a4](url) for the diff.

I know it's not perfect, but it is working for capturing subscriptions from CloudWatch to Kinesis.  There also appeared to be some checkpointing errors in the KinesisConsumer class that I believe i've resolved.  Going to run this for several days in my environment.

**Comment by danotorrey** [comment] 2018-10-11 15:52
@agtcovert Thanks for all of the details.

**Regarding GZIP/Base64 payload**: Very interesting. It be good to understand why the different formats are being sent (to make sure that all cases can be properly handled). I was not able to reproduce the issue (sending `FlowLogs>CloudWatch>Kinesis stream`, and `Lambda logs>CloudWatch>Kinesis` stream). Both cases returned a GZIP payload. Did the Kinesis records (that were not GZIP) originate from a CloudWatch logs `logs put-subscription-filter`?

**Native CloudWatch logs**: This plugin does support processing regular (non FlowLog) CloudWatch logs. To process them, set up a new 'AWS Logs' input (requires a separate Kinesis stream with logs 'put-subscription-filter' that specifically targets the Lambda log group). The main difference between this and the AWS Flow Logs input is that the AWS Flow Logs input automatically parses out all of the [Flow Log-specific fields](https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs.html#flow-log-records), and AWS logs requires most fields to be manually extracted according to user needs.

**Example put-subscription-filter**:
<pre>
aws logs put-subscription-filter \
    --filter-name "UniqueName" \
    --filter-pattern "MatchSomethingInTheLogsHere" \
    --log-group-name "YourLogGroup" \
    --destination-arn "KinesisStreamARN" \
    --role-arn "IAM Kinesis Role ARN"
</pre>

**Checkpointing errors**: Can you please provide the specific errors that occurred and any other relevant details?

**Comment by danotorrey** [comment] 2018-10-18 14:53
@agtcovert I was finally able to reproduce the java.util.zip.ZipException: Not in GZIP format error. In my case, the Kinesis stream data did not originate from CloudWatch (so Graylog was not able to read it). I am still wondering where the log data originated from when the error occurred for you. We can definitely add a check for GZIP or not (and would appreciate your contribution for that), but I think we need to understand where the data came from, so we can verify that it is a valid use case first.

**Comment by danotorrey** [comment] 2018-11-07 15:29
Hi @agtcovert,
Since we have not heard back from you, I am closing this issue for now. Please let us know if you are still experiencing trouble. We're happy to take another look if needed.

**Comment by tj13** [comment] 2019-03-06 07:15
we got the same issue when put-record directly to kinesis stream.

**Comment by tj13** [comment] 2019-03-07 10:31
we got the same issue when put-record directly to kinesis stream.

@danotorrey will this case be support?

**Comment by danotorrey** [comment] 2019-06-05 19:59
Hi @agtcovert,
We are planning to add support for Graylog to read non-GZipped payloads in a future version of Graylog. This would add support for reading those records which were put directly in CloudWatch. We do note have a release date yet, but I will add a reminder to update you once we do.

**Comment by jberneberg** [comment] 2019-06-06 17:08
@danotorrey We have run into this issue as well, and are interested in getting this resolved quickly. Is there a way I can expedite resolution? I have some hours I can devote to resolving this.

**Comment by danotorrey** [comment] 2020-07-14 13:09
The new AWS Kinesis/Cloud Watch integration should solve this. It supports Kinesis streams that contain data that originated from sources other than Cloud Watch (as long as the Kinesis message payload is in encoded text with new line delimiters).

Please see these references for more info:
https://docs.graylog.org/en/3.3/pages/integrations/inputs/aws_kinesis_cloudwatch_input.html
https://www.youtube.com/watch?v=2OHiMWWcp7I

**Closed by danotorrey** 2020-07-14 13:09 UTC
Labels: feature, triaged
